version: '3.8'
services:

  app:
    image: aamitv/app-ci-cd
    container_name: app-ci-cd
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
